# Generated by Django 5.0.1 on 2024-01-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=1000)),
                ('completada', models.BooleanField(default=False)),
            ],
        ),
    ]
